Models/ErrorViewModel.cs
using System;

namespace WebTele.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Program.cs
using System.Xml.Linq;

namespace WebTele.Models
{
    public class Program
    {

        public Program(string name, string desc, string img)
        {
            this.name = name;
            this.description = desc;
            this.img = img;
        }

        public string name { get; set; }
        public string description { get; set; }
        public string img { get; set; }

    }
}

Controllers/GuideController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebTele.Models;

namespace WebTele.Controllers
{
    public class GuideController : Controller
    {
        private readonly ILogger<GuideController> _logger;

        public GuideController(ILogger<GuideController> logger)
        {
            _logger = logger;
        }

        public IActionResult DISNEY()
        {
            ViewData["Programs"] = GetProgramsDisney();

            return View();
        }

        private List<Models.Program> GetProgramsDisney()
        {
            var programs = new List<Models.Program>();

            programs.Add(new Models.Program("Mickey Mouse", "Aventuras del icónico personaje de Disney y sus amigos", "mickey-mouse.jpg"));
            programs.Add(new Models.Program("Vampirina", "Historias de una familia de vampiros que se muda a Pensilvania", "vampirina.jpg"));
            programs.Add(new Models.Program("Muppet Babies", "Aventuras de los famosos Muppets en versión bebé", "muppet-babies.webp"));
            programs.Add(new Models.Program("La casa de Mickey Mouse", "Aventuras de Mickey y sus amigos en la Casa Club", "casa-mickey.jpg"));
            programs.Add(new Models.Program("Puppy Dog Pals", "Aventuras de dos cachorros que resuelven problemas", "puppy-dog-pals.jpg"));
            programs.Add(new Models.Program("PJ Masks", "Aventuras de tres niños que se convierten en héroes por la noche", "pj-masks.jpg"));
            programs.Add(new Models.Program("El maravilloso mundo de Mickey", "Serie de cortometrajes de Mickey y sus amigos", "mundo-mickey.jpeg"));
            programs.Add(new Models.Program("Fancy Nancy", "Historias de una niña que ama la moda y la creatividad", "fancy-nancy.jpg"));
            programs.Add(new Models.Program("Bluey", "Aventuras de una familia de perros en su día a día", "bluey.jpeg"));

            return programs;
        }

        public IActionResult CARTOON()
        {
            ViewData["Programs"] = GetProgramsCartoon();

            return View();
        }

        private List<Models.Program> GetProgramsCartoon()
        {
            var programs = new List<Models.Program>();

            programs.Add(new Models.Program("Hora de Aventuras", "Las aventuras de Finn y Jake en el mundo post-apocalíptico de Ooo", "hora-de-aventuras.webp"));
            programs.Add(new Models.Program("El increíble mundo de Gumball", "Las aventuras cotidianas de Gumball y su familia", "gumball.jpg"));
            programs.Add(new Models.Program("Teen Titans Go!", "Las divertidas aventuras de los superhéroes adolescentes", "teen-titans-go.jpg"));
            programs.Add(new Models.Program("Steven Universe", "La historia de Steven, un niño mitad humano y mitad gema", "steen-universe.jpg"));
            programs.Add(new Models.Program("Victor y Valentino", "Dos hermanos que viven en un pueblo mágico en México", "victor-valentino.jpg"));
            programs.Add(new Models.Program("We Bare Bears", "Las aventuras de tres osos que intentan adaptarse a la vida humana", "we-bare-bears.jpg"));
            programs.Add(new Models.Program("El show de Tom y Jerry", "Las divertidas travesuras del gato y el ratón en situaciones hilarantes, ingeniosas y a menudo caóticas.", "tom-jerry-show.webp"));
            programs.Add(new Models.Program("Ben 10", "Las aventuras de Ben y su reloj Omnitrix que le permite transformarse en diferentes alienígenas", "ben-10.png"));
            programs.Add(new Models.Program("Mao Mao: Héroes de puro corazón", "Las aventuras de un valiente samurái y sus amigos en el Valle Corazón", "mao-mao.jpg"));

            return programs;
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebTele.Models;

namespace WebTele.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Guide/cartoon.cshtml
@{
    ViewData["Title"] = "Cartoon Network";
}
<h1>@ViewData["Title"] - Programas:</h1>

<div class="row row-cols-1 row-cols-md-3 g-4">
    @foreach (var item in ViewData["Programs"] as List<WebTele.Models.Program>)
    {
        <div class="col" style="margin-bottom: 20px;">
            <div class="card">
                <img src="/resources/@item.img" class="card-img-top" style="min-height: 200px; min-width: 300px; max-height: 200px;" />
                <div class="card-body">
                    <h5 class="card-title">@item.name</h5>
                    <p class="card-text">@item.description</p>
                </div>
            </div>
        </div>
    }
</div>

Views/Guide/disney.cshtml
@{
    ViewData["Title"] = "Disney Junior";
}
<h1>@ViewData["Title"] - Programas:</h1>

<div class="row row-cols-1 row-cols-md-3 g-4">
    @foreach (var item in ViewData["Programs"] as List<WebTele.Models.Program>)
    {
        <div class="col" style="margin-bottom: 20px;">
            <div class="card">
                <img src="/resources/@item.img" class="card-img-top" style="min-height: 200px; min-width: 300px; max-height: 200px;" />
                <div class="card-body">
                    <h5 class="card-title">@item.name</h5>
                    <p class="card-text">@item.description</p>
                </div>
            </div>
        </div>
    }
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Canales";
}

<div class="text-center">
    <div class="row">
        <div class="col-sm-6">
            <div class="card">
                <div class="card-body">
                    <img src="/resources/disney-junior.png" style="max-width: 100%; max-height: 286px">
                    <p class="card-text">Disney Channel es un canal de televisión por suscripción para niños y jóvenes que ofrece una programación llena de magia, aventuras y música. Destaca por sus populares series y películas originales, además de su compromiso con el público joven y la familia.</p>
                    <a class="btn btn-primary" asp-area="" asp-controller="Guide" asp-action="DISNEY">Ver programas</a>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="card">
                <div class="card-body">
                    <img src="/resources/cartoon-network.jpg" style="max-width: 100%; max-height: 286px">
                    <p class="card-text">Cartoon Network es un canal de televisión para niños y jóvenes con una amplia variedad de programas de dibujos animados divertidos y emocionantes. Destaca por su programación creativa y original que deleita a su público joven.</p>
                    <a class="btn btn-primary" asp-area="" asp-controller="Guide" asp-action="CARTOON">Ver programas</a>
                </div>
            </div>
        </div>
    </div>

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebTele</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebTele</a>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container" style="display:flex; justify-content:space-between">
            Copyright &copy; 2023 - Bruno Agostini

            <div>
                <a href="https://github.com/MinecraftDorado"><i class="fab fa-github-square fa-2x" style="color:black; padding-right: 12.5px;"></i></a>
                <a href="mailto:contacto@brunoagostini.com?subject=Programaci%C3%B3n%202%20-%20Parcial%202"><i class="far fa-envelope fa-2x" style="color:black"></i></a>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>